CONTRIBUTING.md, README.md, pom.xml, src/main/java/liquibase/ext/mongodb/changelog/MongoHistoryService.java, src/main/java/liquibase/ext/mongodb/database/MongoClientDriver.java, src/main/java/liquibase/ext/mongodb/database/MongoConnection.java, src/main/java/liquibase/ext/mongodb/lockservice/MongoChangeLogLock.java, src/main/java/liquibase/nosql/changelog/AbstractNoSqlHistoryService.java, src/main/java/liquibase/nosql/database/AbstractNoSqlConnection.java, src/main/java/liquibase/nosql/database/AbstractNoSqlDatabase.java, src/main/java/liquibase/nosql/lockservice/AbstractNoSqlLockService.java, src/test/java/liquibase/ext/mongodb/changelog/AdjustChangeLogCollectionStatementIT.java, src/test/java/liquibase/ext/mongodb/configuration/MongoConfigurationTest.java, src/test/java/liquibase/ext/mongodb/database/MongoConnectionTest.java, src/test/java/liquibase/ext/mongodb/lockservice/AdjustChangeLogLockCollectionStatementIT.java, src/test/resources/liquibase.properties
Fix #56 
Can provide user and password in CLI liquibase.properties
Removed commons-lang3 so that not required as an additional /lib dependency for CLI
=> Issue-56: User and Password not picked from liquibase.properties

src/main/java/liquibase/ext/mongodb/changelog/AdjustChangeLogCollectionStatement.java, src/main/java/liquibase/ext/mongodb/changelog/GetMaxChangeSetSequenceStatement.java, src/main/java/liquibase/ext/mongodb/database/MongoClientDriver.java, src/main/java/liquibase/ext/mongodb/database/MongoConnection.java, src/main/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabase.java, src/main/java/liquibase/ext/mongodb/lockservice/AdjustChangeLogLockCollectionStatement.java, src/main/java/liquibase/ext/mongodb/lockservice/ReplaceChangeLogLockStatement.java, src/main/java/liquibase/ext/mongodb/lockservice/SelectChangeLogLockStatement.java, src/main/java/liquibase/ext/mongodb/statement/AbstractMongoStatement.java, src/main/java/liquibase/ext/mongodb/statement/AbstractRunCommandStatement.java, src/main/java/liquibase/ext/mongodb/statement/AdminCommandStatement.java, src/main/java/liquibase/ext/mongodb/statement/CountCollectionByNameStatement.java, src/main/java/liquibase/ext/mongodb/statement/CountDocumentsInCollectionStatement.java, src/main/java/liquibase/ext/mongodb/statement/DeleteManyStatement.java, src/main/java/liquibase/ext/mongodb/statement/DropAllCollectionsStatement.java, src/main/java/liquibase/ext/mongodb/statement/FindAllStatement.java, src/main/java/liquibase/ext/mongodb/statement/FindOneAndUpdateStatement.java, src/main/java/liquibase/ext/mongodb/statement/UpdateManyStatement.java, src/main/java/liquibase/nosql/changelog/AbstractNoSqlHistoryService.java, src/main/java/liquibase/nosql/statement/AbstractNoSqlStatement.java, src/test/java/liquibase/ext/AbstractMongoIntegrationTest.java, src/test/java/liquibase/ext/MongoLiquibaseIT.java, src/test/java/liquibase/ext/mongodb/TestUtils.java, src/test/java/liquibase/ext/mongodb/changelog/AdjustChangeLogCollectionStatementIT.java, src/test/java/liquibase/ext/mongodb/lockservice/AdjustChangeLogLockCollectionStatementIT.java, src/test/java/liquibase/ext/mongodb/statement/CountCollectionByNameStatementIT.java, src/test/java/liquibase/ext/mongodb/statement/MongoStatementIT.java
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1271) by [Unito](https://www.unito.io/learn-more)
=> Adjust NoSql APIs

README.md, src/main/java/liquibase/ext/mongodb/statement/AbstractRunCommandStatement.java, src/main/java/liquibase/ext/mongodb/statement/AdminCommandStatement.java, src/main/java/liquibase/ext/mongodb/statement/FindOneAndUpdateStatement.java, src/test/java/liquibase/ext/mongodb/change/AdminCommandChangeTest.java, src/test/java/liquibase/ext/mongodb/statement/AdminCommandStatementIT.java, src/test/resources/liquibase/ext/changelog.admin-command.test.xml
Fixes #111
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1352) by [Unito](https://www.unito.io/learn-more)
=> Issue-111: Is adminCommand really connected to the admin DB?

pom.xml, test-project/pom.xml
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1374) by [Unito](https://www.unito.io/learn-more)
=> prepare ITs for next development iteration 4.3.1.2-SNAPSHOT

pom.xml, test-project/pom.xml
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1404) by [Unito](https://www.unito.io/learn-more)
=> prepare ITs for next development iteration 4.3.3-SNAPSHOT

.github/workflows/pull-request-labeled-release.yml, pom.xml
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1721) by [Unito](https://www.unito.io)
=> Release 4.3.5

pom.xml
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1868) by [Unito](https://www.unito.io)
=> Updates for 4.4.0 release

pom.xml
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1964) by [Unito](https://www.unito.io)
=> Version Bumped to 4.4.2

src/main/java/liquibase/ext/mongodb/precondition/CollectionExistsPrecondition.java, src/main/resources/META-INF/services/liquibase.precondition.Precondition, src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd, src/test/java/liquibase/ext/MongoLiquibaseIT.java, src/test/resources/liquibase/ext/changelog.insert-precondition.test.xml
Summary:
* For our migration changelog to work we need collections exists precondition, so here is the PR for it.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1966) by [Unito](https://www.unito.io)
=> Add collection exists precondition

.github/workflows/pull-request.yml, src/main/java/liquibase/nosql/executor/NoSqlExecutor.java
Adds integration test run to pull_request github action targets
=> Run integration tests on pull request runs

pom.xml
Currently tests are not running in CI. This PR addresses this issue.
=> Fix test runner

src/main/java/liquibase/nosql/changelog/AbstractNoSqlItemToDocumentConverter.java
Fixes for changes in core PR [2947](https://github.com/liquibase/liquibase/pull/2947/)
=> Fixes for core-pr-2947

.github/workflows/release-published.yml, src/main/resources/www.liquibase.org/xml/ns/mongodb/liquibase-mongodb-1.0.xsd, src/main/resources/www.liquibase.org/xml/ns/mongodb/liquibase-mongodb-latest.xsd, src/test/resources/liquibase/ext/changelog.admin-command.test.xml, src/test/resources/liquibase/ext/changelog.changeTypesMix.xml, src/test/resources/liquibase/ext/changelog.changeTypesMix_rollback.xml, src/test/resources/liquibase/ext/changelog.create-collection.test.xml, src/test/resources/liquibase/ext/changelog.create-index.test.xml, src/test/resources/liquibase/ext/changelog.create-users.test.xml, src/test/resources/liquibase/ext/changelog.drop-users.test.xml, src/test/resources/liquibase/ext/changelog.implicit-rollback.test.xml, src/test/resources/liquibase/ext/changelog.insert-many.test.xml, src/test/resources/liquibase/ext/changelog.insert-one.test.xml, src/test/resources/liquibase/ext/changelog.insert-precondition.test.xml, src/test/resources/liquibase/ext/changelog.insert-tags.test.xml, src/test/resources/liquibase/ext/changelog.rollback-insert-many.test.xml, src/test/resources/liquibase/ext/changelog.run-command.test.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/adminCommand.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/createCollection.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/createIndex.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/dropCollection.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/dropIndex.json, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/dropIndex.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/dropIndex.yaml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/insertMany.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/insertOne.xml, src/test/resources/liquibase/harness/compatibility/foundational/changelogs/nosql/runCommand.xml
Rename and add numeration to xsd schemes.
=> DAT-12346 Rename and publish xsd schemes

.github/workflows/release-published.yml
XSD uploads should not have a prerequisite step
=> hotfix xsd uploads

pom.xml, src/main/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabase.java
This reverts commit 865565c82564655a0fb6502913e4202724bb6ff9.
=> [DAT-15624] Fix conflict between core and extension dropAll fixes

.github/workflows/build-nightly.yml
https://datical.atlassian.net/browse/DAT-15348
feat(build-nightly.yml): add a nightly build workflow to build the ex…
=> DAT-15348   DevOps :: run nightly builds for extensions against core master-snapshot

pom.xml, src/main/java/liquibase/ext/mongodb/database/MongodbConnectionPatterns.java, src/main/resources/META-INF/services/liquibase.database.jvm.ConnectionPatterns
This code is based on the https://github.com/liquibase/liquibase/pull/4705
=> [DAT-15338] Add mongodb connection patterns to hide credentials in logs

.github/workflows/attach-artifact-release.yml, .github/workflows/build-nightly.yml, .github/workflows/create-release.yml, .github/workflows/release-published.yml, .github/workflows/snyk-nightly.yml
…0.5.1 for improved functionality and bug fixes
=> DAT-16080 DevOps :: Extension Nightly Builds Failing

.github/workflows/codeql.yml
This needs to be merged before: https://github.com/liquibase/build-logic/pull/109
=> DAT-15598  DevOps :: Create reusable workflow for CodeQL scanning

.github/workflows/attach-artifact-release.yml, .github/workflows/build-nightly.yml, .github/workflows/codeql.yml, .github/workflows/create-release.yml, .github/workflows/release-published.yml, .github/workflows/test.yml, pom.xml
feat(pom.xml): add dependencies for lombok, mockito-junit-jupiter, jackson-databind, assertj-core, jsonassert, and json for improved functionality and testing
=> DAT-16142  DevOps :: Liquibase MongoDB Extension : sonar cloud scans showing as 0.0% Coverage

.github/workflows/attach-artifact-release.yml, .github/workflows/build-nightly.yml, .github/workflows/codeql.yml, .github/workflows/create-release.yml, .github/workflows/release-published.yml, .github/workflows/test.yml
Reverts liquibase/liquibase-mongodb#513
=> Revert "build(deps): bump liquibase/build-logic from 0.6.6 to 0.6.8"

.github/workflows/test.yml, FerretDB.md
fixes https://github.com/actions/runner-images/issues/9557
=> DAT-17414 upgrade docker compose to v2

src/main/java/liquibase/nosql/parser/json/JsonNoSqlChangeLogParser.java
=> Use the Database object from scope in the supports method
