- .gitignore
- .travis.yml
- src/test/java/liquibase/ext/mongodb/TestUtils.java
Adjust travis config to run the tests on every build. Merging this to master and rebasing the PR will let us know if upgrading the Mongo DB driver will break any of the automated tests.
Assuming the Automated tests are pretty comprehensive, I think we'd be okay to merge the PR although might want to consider cutting an `@next` style of release for beta testers or something like that.
> Travis Tests

- src/main/java/liquibase/ext/mongodb/lockservice/MongoLockService.java
- src/main/resources/META-INF/services/liquibase.changelog.ChangeLogHistoryService
- src/main/resources/META-INF/services/liquibase.database.Database
- src/main/resources/META-INF/services/liquibase.database.DatabaseConnection
- src/main/resources/META-INF/services/liquibase.executor.Executor
- src/main/resources/META-INF/services/liquibase.lockservice.LockService
- src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Since the migration to 4.0, there are additional META-INF files that need to be added. In addition, there are two places in the MongoLockService.java that had a null database object.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-621) by [Unito](https://www.unito.io/learn-more)
> Add missing META-INF files and fix two tests

- pom.xml
In recent [Travis builds](https://travis-ci.com/github/liquibase/liquibase-mongodb), the integration tests are failing but the build still succeeds. 
The maven-failsafe-plugin requires an addition execution phase in order to verify the test results. This change will fail a build when any integration tests fail.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-616) by [Unito](https://www.unito.io/learn-more)
> Build should fail if integration tests do not pass

- src/main/java/liquibase/ext/mongodb/database/MongoClientDriver.java
- src/main/java/liquibase/ext/mongodb/database/MongoConnection.java
- src/main/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabase.java
- src/main/java/liquibase/ext/mongodb/executor/MongoExecutor.java
During `liquibase update` the current mongodb ext version will fail with an `unknown database` error. These changes proper implements a custom driver that satisfies liquibase core and allows updates to successfully complete.
> Fixes unknown database during update

- README.md
- src/main/java/liquibase/ext/mongodb/change/AdminCommandChange.java
- src/main/java/liquibase/ext/mongodb/change/CreateCollectionChange.java
- src/main/java/liquibase/ext/mongodb/change/CreateIndexChange.java
- src/main/java/liquibase/ext/mongodb/change/DropCollectionChange.java
- src/main/java/liquibase/ext/mongodb/change/DropIndexChange.java
- src/main/java/liquibase/ext/mongodb/change/InsertOneChange.java
- src/main/java/liquibase/ext/mongodb/change/RunCommandChange.java
- src/main/java/liquibase/ext/mongodb/statement/DropIndexStatement.java
- src/main/java/liquibase/nosql/database/AbstractNoSqlDatabase.java
- src/main/resources/META-INF/services/liquibase.change.Change
- src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd
- src/test/java/liquibase/ext/MongoLiquibaseIT.java
- src/test/java/liquibase/ext/MongoLiquibaseJsonIT.java
- src/test/java/liquibase/ext/mongodb/TestUtils.java
- src/test/java/liquibase/ext/mongodb/change/AdminCommandChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/CreateCollectionChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/CreateIndexChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/InsertManyChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/InsertOneChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/RunCommandChangeTest.java
- src/test/resources/liquibase/ext/changelog.implicit-rollback.test.xml
- src/test/resources/liquibase/ext/changelog.rollback-insert-many.test.xml
Fix #38
Fixed Explicit Rollback 
Added Implicit Rollbacks for createCollection and createIndex with respective dropCollection and dropIndex Inverses
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-897) by [Unito](https://www.unito.io/learn-more)
> Issue-38: Rollback doesn't work with liquibase-mongodb-4.0.0.2 extension

- README.md
- pom.xml
- src/main/java/liquibase/ext/mongodb/change/AbstractMongoChange.java
- src/main/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabase.java
- src/main/java/liquibase/nosql/database/AbstractNoSqlDatabase.java
- src/main/java/liquibase/nosql/lockservice/AbstractNoSqlLockService.java
- src/main/java/liquibase/nosql/parser/json/JsonNoSqlChangeLogParser.java
- src/test/java/liquibase/ext/mongodb/TestUtils.java
- src/test/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabaseTest.java
- src/test/resources/liquibase.properties
Fix #53 
Route Cause is missing jackson libraries in liquibase/lib. 
In this PR just added the liquibase.properties and made dropAll work from CLI by default without specifying schemas. 
Fixed WARNING The following SQL may change each run and therefore is possibly ...
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-901) by [Unito](https://www.unito.io/learn-more)
> Issue-53: Pre-released 4.1.2-SNAPSHOT.jar JSON Format update fails on insertMany

- src/main/java/liquibase/ext/mongodb/precondition/ExpectedDocumentCountPrecondition.java
- src/main/resources/META-INF/services/liquibase.precondition.Precondition
- src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd
- src/test/java/liquibase/ext/MongoLiquibaseIT.java
- src/test/java/liquibase/ext/MongoLiquibaseJsonIT.java
- src/test/resources/liquibase/ext/changelog.insert-precondition.test.xml
- src/test/resources/liquibase/ext/json/changelog.insert-precondition.test.json
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1105) by [Unito](https://www.unito.io/learn-more)
> Added ExpectedDocumentCountPrecondition

- src/main/java/liquibase/ext/mongodb/change/CreateCollectionChange.java
- src/main/java/liquibase/ext/mongodb/changelog/AdjustChangeLogCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/lockservice/AdjustChangeLogLockCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/statement/AbstractCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/statement/AbstractRunCommandStatement.java
- src/main/java/liquibase/ext/mongodb/statement/AdminCommandStatement.java
- src/main/java/liquibase/ext/mongodb/statement/BsonUtils.java
- src/main/java/liquibase/ext/mongodb/statement/CountCollectionByNameStatement.java
- src/main/java/liquibase/ext/mongodb/statement/CreateCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/statement/RunCommandStatement.java
- src/test/java/liquibase/ext/mongodb/TestUtils.java
- src/test/java/liquibase/ext/mongodb/change/CreateCollectionChangeTest.java
- src/test/java/liquibase/ext/mongodb/statement/CountCollectionByNameStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/CreateCollectionStatementIT.java
Changed `CreateCollectionStatement` to execute as a mongoDB `runCommand` so that it supports all available server options.
Made `AbstractCollectionStatement.toJs()` method abstract and fixed the `CountCollectionByNameStatement` implementation of it.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1117) by [Unito](https://www.unito.io/learn-more)
> Add support for all available options for CreateCollectionChange

- README.md
- src/main/java/liquibase/ext/mongodb/database/MongoClientDriver.java
- src/main/java/liquibase/ext/mongodb/database/MongoConnection.java
- src/main/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabase.java
- src/main/java/liquibase/nosql/database/AbstractNoSqlConnection.java
- src/test/java/liquibase/ext/mongodb/database/MongoClientDriverTest.java
- src/test/java/liquibase/ext/mongodb/database/MongoConnectionTest.java
- src/test/java/liquibase/ext/mongodb/database/MongoLiquibaseDatabaseTest.java
fixes #66
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1148) by [Unito](https://www.unito.io/learn-more)
> Issue-66: Atlas cluster connection string

- README.md
- src/main/java/liquibase/ext/mongodb/changelog/MongoHistoryService.java
- src/main/java/liquibase/ext/mongodb/statement/CreateCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/statement/FindOneAndUpdateStatement.java
- src/main/java/liquibase/nosql/changelog/AbstractNoSqlHistoryService.java
- src/test/java/liquibase/ext/MongoLiquibaseIT.java
- src/test/java/liquibase/ext/MongoLiquibaseJsonIT.java
- src/test/resources/liquibase/ext/changelog.insert-tags.test.xml
- src/test/resources/liquibase/ext/json/changelog.insert-tags.json
Fixes #70 
Fixed last state tag. tagDatabase works out of the box. Added integration tests for xml and json/
`
MongoLiquibaseIT#testTags->changelog.insert-tags.test.xml
MongoLiquibaseJsonIT#testTags->changelog.insert-tags.json
`
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1150) by [Unito](https://www.unito.io/learn-more)
> Tag the current database state

- src/main/java/liquibase/ext/mongodb/statement/AbstractRunCommandStatement.java
- src/main/java/liquibase/ext/mongodb/statement/BsonUtils.java
- src/main/java/liquibase/ext/mongodb/statement/CreateCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/statement/InsertOneStatement.java
- src/main/java/liquibase/ext/mongodb/statement/RunCommandStatement.java
- src/test/java/liquibase/ext/mongodb/changelog/AdjustChangeLogCollectionStatementIT.java
- src/test/java/liquibase/ext/mongodb/lockservice/AdjustChangeLogLockCollectionStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/CreateCollectionStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/CreateCollectionStatementTest.java
- src/test/java/liquibase/ext/mongodb/statement/InsertOneStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/MongoStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/RunCommandStatementIT.java
The error handling was more complicated than I had initially expected.
Wanted to raise this PR to give early visibility of the type of checking needed when using `runCommand` for this operation.
Noting that:
* InsertMany will be slightly more complicated than this case - due to the potential for multiple documents failing to insert.
* There is currently **NO** error checking of server responses from the existing `runCommand` and `adminCommand` operations. This could pose a risk in failing to report commands that failed. I think this could be covered in a new issue (happy to log it later).
Finally added an error check test for `CreateCollectionStatement` as I was paranoid errors are no longer checked, but this is not the case as the server reports these differently from the `insert` …
> Convert insertOne statement to execute as a runCommand operation

- src/main/java/liquibase/ext/mongodb/statement/InsertManyStatement.java
- src/main/java/liquibase/ext/mongodb/statement/InsertOneStatement.java
- src/test/java/liquibase/ext/mongodb/statement/InsertManyStatementIT.java
Converts InsertMany to `runCommand` style.
Refactored InsertOne to extend this and minimize duplication - i.e. keeps the code DRY.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1182) by [Unito](https://www.unito.io/learn-more)
> Issue #90 Convert InsertMany to execute as a runCommand

- src/main/java/liquibase/ext/mongodb/changelog/AdjustChangeLogCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/changelog/MongoHistoryService.java
- src/main/java/liquibase/ext/mongodb/lockservice/AdjustChangeLogLockCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/lockservice/MongoLockService.java
- src/main/java/liquibase/nosql/changelog/AbstractNoSqlHistoryService.java
- src/main/java/liquibase/nosql/lockservice/AbstractNoSqlLockService.java
- src/test/java/liquibase/ext/mongodb/changelog/AdjustChangeLogCollectionStatementIT.java
- src/test/java/liquibase/ext/mongodb/changelog/MongoHistoryServiceTest.java
- src/test/java/liquibase/ext/mongodb/lockservice/AdjustChangeLogLockCollectionStatementIT.java
- src/test/java/liquibase/ext/mongodb/lockservice/MongoLockServiceTest.java
> Issue 67: Supports validator read directly from database

- src/main/java/liquibase/ext/mongodb/change/CreateCollectionChange.java
- src/main/java/liquibase/ext/mongodb/change/CreateIndexChange.java
- src/main/java/liquibase/ext/mongodb/statement/AbstractRunCommandStatement.java
- src/main/java/liquibase/ext/mongodb/statement/BsonUtils.java
- src/main/java/liquibase/ext/mongodb/statement/CreateIndexStatement.java
- src/main/java/liquibase/ext/mongodb/statement/InsertManyStatement.java
- src/main/java/liquibase/ext/mongodb/statement/InsertOneStatement.java
- src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd
- src/test/java/liquibase/ext/mongodb/TestUtils.java
- src/test/java/liquibase/ext/mongodb/statement/BsonUtilsTest.java
- src/test/java/liquibase/ext/mongodb/statement/CreateCollectionStatementTest.java
- src/test/java/liquibase/ext/mongodb/statement/CreateIndexStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/InsertManyStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/InsertOneStatementIT.java
- src/test/resources/liquibase/ext/changelog.implicit-rollback.test.xml
Fixes #90
Fixes #74
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1185) by [Unito](https://www.unito.io/learn-more)
> Issue 90: Convert CreateIndex to execute as a runCommand

- README.md
- src/main/java/liquibase/ext/mongodb/statement/CreateCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/statement/CreateIndexStatement.java
- src/main/java/liquibase/ext/mongodb/statement/DropAllCollectionsStatement.java
- src/main/java/liquibase/ext/mongodb/statement/DropCollectionStatement.java
- src/main/java/liquibase/ext/mongodb/statement/DropIndexStatement.java
- src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd
- src/test/java/liquibase/ext/mongodb/change/CreateCollectionChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/CreateIndexChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/DropIndexChangeTest.java
- src/test/java/liquibase/ext/mongodb/statement/DropCollectionStatementIT.java
- src/test/java/liquibase/ext/mongodb/statement/DropIndexStatementIT.java
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1256) by [Unito](https://www.unito.io/learn-more)
> Issue 90: Convert DropCollection to execute as a runCommand

- src/main/java/liquibase/ext/mongodb/statement/FindOneAndUpdateStatement.java
- src/test/java/liquibase/ext/mongodb/statement/FindOneAndUpdateStatementIT.java
Converts the `FindOneAndUpdateStatement` to execute as a `runCommand` statement with a supporting constructor for other supported options.
NOTE: The command name is changed from `updateLastTag` to `findAndModify`
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1332) by [Unito](https://www.unito.io/learn-more)
> Issue #90 Convert FindOneAndUpdateStatement to use runCommand

- src/main/java/liquibase/ext/mongodb/statement/BsonUtils.java
> fix: add iterable codec provider to the default document codec list

- pom.xml
It's a detail but that makes the links provided by Dependabot incorrect.
> Fix GitHub URL in pom

- src/main/java/liquibase/ext/mongodb/statement/AbstractRunCommandStatement.java
The `ResponseDocument` we get back from DocumentDB emulating MongoDB 4.0 during a migration has an attribute, `ok` which is an `Integer`. 
Additionally, DocumentDB does not support document validation, so: something along the lines of `System.setProperty("liquibase.mongodb.supportsValidator", "false");` will be necessary
This addresses the issue described in https://github.com/liquibase/liquibase-mongodb/issues/244
> DocumentDB Issue

- pom.xml
- src/main/java/liquibase/ext/mongodb/lockservice/ReplaceChangeLogLockStatement.java
Run databasechangelock update with upsert "true" only the first time.
This works in MongoDb and is needed in Azure CosmoDb's MongoDB Api.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2163) by [Unito](https://www.unito.io)
> Run databasechangelock update with upsert "true" only the first time.

- pom.xml
Without this option, the `index.htm` file is added to the released jar file
> [DAT-14184] Remove index.htm file from released artifact

- .github/workflows/create-release.yml
- pom.xml
More details here: https://github.com/liquibase/build-logic/pull/32
feat(create-release.yml): add update-version job to update extension version before building
refactor(create-release.yml): remove git user configuration and pom.xml version update from build job and move it to update-version job
feat(pom.xml): add maven-release-plugin to configure scmCommentPrefix for version bumping commit messages
> DAT-15071 Automatically bump version on mongodb via the release workflow

- src/main/java/liquibase/ext/mongodb/change/AbstractMongoChange.java
- src/main/java/liquibase/ext/mongodb/change/AdminCommandChange.java
- src/main/java/liquibase/ext/mongodb/change/CreateCollectionChange.java
- src/main/java/liquibase/ext/mongodb/change/CreateIndexChange.java
- src/main/java/liquibase/ext/mongodb/change/DropIndexChange.java
- src/main/java/liquibase/ext/mongodb/change/InsertManyChange.java
- src/main/java/liquibase/ext/mongodb/change/InsertOneChange.java
- src/main/java/liquibase/ext/mongodb/change/RunCommandChange.java
- src/test/java/liquibase/ext/MongoLiquibaseIT.java
- src/test/java/liquibase/ext/MongoLiquibaseJsonIT.java
- src/test/java/liquibase/ext/mongodb/change/AdminCommandChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/CreateCollectionChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/CreateIndexChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/DropIndexChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/InsertManyChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/InsertOneChangeTest.java
- src/test/java/liquibase/ext/mongodb/change/RunCommandChangeTest.java
- src/test/java/liquibase/ext/mongodb/changelog/MongoHistoryServiceIT.java
Generate checksum normalizing texts so changes as adding white spaces and new lines won't break the checksum, making Mongodb extensions compliant with core changes.
Built upon DAT-15279
> [DAT-15373] Fix checksum empty spaces validation

- .github/workflows/attach-artifact-release.yml
https://github.com/liquibase/liquibase-mongodb/actions/runs/10991845947/job/30515024465 failed with ```Error: This request has been automatically failed because it uses a deprecated version of `actions/download-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/```
> changed `extension-attach-artifact-release` version from 0.7.8 to main

- pom.xml
- src/main/java/liquibase/ext/mongodb/database/MongoClientDriver.java
- src/main/java/liquibase/ext/mongodb/database/MongoConnection.java
- src/test/java/liquibase/ext/mongodb/database/MongoConnectionTest.java
Tested on Built Jar-s with different core and pro JAR-s stored in `liquibase/lib`.
Only OSS Jar is present:
Commercial Jar is present and Pro license is valid:
> DAT-18810: app naming updated, it contains now versions of core/pro liquibase and extension version also.

- src/main/java/liquibase/ext/mongodb/statement/AbstractRunCommandStatement.java
- src/main/java/liquibase/nosql/executor/NoSqlExecutor.java
- src/test/java/liquibase/ext/mongodb/statement/RowsAffectedStatementIT.java
This PR addresses the issue where rows affected are incorrectly shown as -1 in the update summary for MongoDB operations. It implements proper tracking of affected documents for various MongoDB commands including collection operations and document manipulations.
- Added document count tracking in AbstractRunCommandStatement
- Implemented rows affected extraction from MongoDB command responses
- Added support for different operation types (insert, update, delete, collection ops)
- Updated NoSqlExecutor to properly handle rows affected scope
Added new integration tests (RowsAffectedStatementIT) covering:
- Collection creation/deletion
- Single document insertion
- Multiple document insertion
- Combined operations
Result:
> Fix rows affected reporting for MongoDB operations

- .github/workflows/build-master.yml
This pull request introduces a new GitHub Actions workflow to automate the build and publishing process for the main/master branch. The workflow includes steps for setting up the environment, obtaining the latest commit SHA and timestamp, and publishing both master-SNAPSHOT and commit-SNAPSHOT versions of the artifact.
Key changes include:
* [`.github/workflows/build-master.yml`](diffhunk://#diff-53f6a76fa86b1994f9da743d84e130a48058a0d0657949c412c203d5f0aedfe8R1-R63): Created a new workflow named "Build Main/Master SNAPSHOT" that triggers on pushes to the main branch and workflow dispatch events.
* Setup job: Added steps to check out the repository, get the latest merge commit SHA, and get the current timestamp.
* Build and publish job: Added steps to set up Java, version the artifact as …
> ✨ DAT19697

- src/main/java/liquibase/ext/mongodb/changelog/MongoHistoryService.java
- src/main/java/liquibase/ext/mongodb/lockservice/MongoLockService.java
If the database connection has been closed, like would happen when using Oracle with sqlplus and the timeout is exceeded, this call will fail because there is no way to obtain the product name from a closed database connection.
> fix lock and history service with closed database connection (DAT-19849)

- src/main/java/liquibase/ext/mongodb/lockservice/ReplaceChangeLogLockStatement.java
- src/test/java/liquibase/ext/mongodb/lockservice/ReplaceChangeLogLockStatementIT.java
The current `update` method of `ReplaceChangeLogLockStatement` is not safe. It allows multiple owner (identified by the `lockedBy` field) to acquire the lock simultaneously. And it also allows the release by a different owner. There isn't any fence in the current implementation:
https://github.com/liquibase/liquibase-mongodb/blob/5582bcd6450364608872bd6dd21d03a482f4cda7/src/main/java/liquibase/ext/mongodb/lockservice/ReplaceChangeLogLockStatement.java#L77-L84
Indeed, by running the following code with the latest liquibase-mongodb version there will be also multiple exceptions:
```java
public final class Main {
public static void main(final String[] args) throws Exception {
for (var i = 0; i < 16; i++) {
Executors.newSingleThreadExecutor().execute(() ->
{
try (
var db = …
```
> Fix ReplaceChangeLogLockStatement

- src/main/java/liquibase/ext/mongodb/database/MongoConnection.java
This PR adds an override in MongoConnection of a new getVisibleUrl() method. It returns the connection string. This method will be released as a part of Liquibase 4.33.
> Added override of DatabaseConnection.getVisibleUrl() method for reporting purposes
